version: 0.5.1-{build}
environment:
  PYTHON: "C:\\python310"
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYVER: py38
      TOXENV: py38-conancurrent

platform:
  - x64
  - x86

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip3 install conan --upgrade
  - conan user
  - conan install initial-settings.py
  - conan --version

build_script:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - mkdir build
  - echo conan install . -s build_type=Release -s arch=x86 --build=missing > x86.bat
  - echo conan install . -s build_type=Release -s arch=x86_64 --build=missing > x64.bat
  - call %PLATFORM%.bat
  - conan package .

test_script:
  - conan install cmake/3.22.0@/ -g virtualenv
  - activate
  - cd build
  - ctest

after_build:
  - if exist %USERPROFILE%\.conan\data\3space rmdir %USERPROFILE%\.conan\data\3space /S /Q
  - if exist %USERPROFILE%\.conan\data\detours rmdir %USERPROFILE%\.conan\data\detours /S /Q
  - powershell Compress-Archive package/* open-siege-%APPVEYOR_BUILD_VERSION%-%PLATFORM%.zip

artifacts:
  - path: open-siege-$(APPVEYOR_BUILD_VERSION)-$(PLATFORM).zip
    name: OpenSiege

cache:
  - '%USERPROFILE%/.conan/data'
  - '%LOCALAPPDATA%/pip/cache'
  - extender/darkstar.proxy/impl/mingw.7z

branches:
  except:
    - preview

deploy:
  - release: Open Siege Preview Release
    description: "See release notes for information about this release: https://github.com/3space-studio/3space-studio/wiki/Release-Notes"
    provider: GitHub
    auth_token:
      secure: j9gRSLHiiIC4nZ4dake8rl5AKZO+nirkNT28Fw53gDZ5F8/Os6F6NPc7OH6db7zB
    artifact: OpenSiege
    draft: false
    skip_tags: true
    prerelease: true
    force_update: true
    tag: preview
    on:
      branch: master
      APPVEYOR_REPO_TAG: false
  - tag: $(APPVEYOR_REPO_TAG_NAME)
    release: Open Siege $(APPVEYOR_REPO_TAG_NAME) Release
    description: "See release notes for information about this release: https://github.com/3space-studio/3space-studio/wiki/Release-Notes"
    provider: GitHub
    auth_token:
      secure: j9gRSLHiiIC4nZ4dake8rl5AKZO+nirkNT28Fw53gDZ5F8/Os6F6NPc7OH6db7zB
    artifact: OpenSiege
    draft: false
    prerelease: false
    on:
      branch: master
      APPVEYOR_REPO_TAG: true
