  version: 1.0.{build}
  environment:
    PYTHON: "C:\\Python38-x64\\python.exe"
  platform:
    - x64
    - x86

  install:
    - cmd: >-
        echo "Downloading conan..."
        set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\Python\Python38\Scripts\
        "%PYTHON%" -m pip install --user conan
        conan user
        conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
        conan --version

  build_script:
    - cmd: mkdir build
    - cmd: conan install . -s build_type=Release
    - cmd: conan build .

  test_script:
    - cmd: cd build
    - cmd: ctest