version: 0.5.1-{build}
environment:
  PYTHON: "C:\\python310"
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYVER: py38
      TOXENV: py38-conancurrent
      CMAKE_GENERATOR: "Visual Studio 16 2019"

platform:
  - x64
  - x86

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip3 install conan --upgrade
  - conan user
  - conan install initial-settings.py
  - conan --version

build_script:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - mkdir build
  - echo conan install . -s build_type=Release -s arch=x86 --build=missing > x86.bat
  - echo conan install . -s build_type=Release -s arch=x86_64 --build=missing > x64.bat
  - call %PLATFORM%.bat
  - conan package .

test_script:
  - conan install cmake/3.22.0@/ -g virtualenv
  - activate
  - cd build
  - ctest

after_build:
  - if exist %USERPROFILE%\.conan\data\3space rmdir %USERPROFILE%\.conan\data\3space /S /Q
  - if exist %USERPROFILE%\.conan\data\detours rmdir %USERPROFILE%\.conan\data\detours /S /Q
  - powershell Compress-Archive package/* 3space-studio-%APPVEYOR_BUILD_VERSION%-%PLATFORM%.zip

artifacts:
  - path: 3space-studio-$(APPVEYOR_BUILD_VERSION)-$(PLATFORM).zip
    name: 3spaceStudio

cache:
  - '%USERPROFILE%/.conan/data'
  - pip3 cache dir > temp && set /p PIP_CACHE=<temp && %PIP_CACHE%

deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: 3Space Studio $(APPVEYOR_REPO_TAG_NAME) Release
  description: "See release notes for information about this release: https://github.com/3space-studio/3space-studio/wiki/Release-Notes"
  provider: GitHub
  auth_token:
    secure: hD8hzQeP3c5jJuk/pMwouuz4wI8VdHDfGlyoTYLrWur9mLHj3lbMP7R37eHRd2Gy
  artifact: 3spaceStudio
  draft: false
  prerelease: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
