version: 1.0.{build}
environment:
  PYTHON: "C:\\Python37"
  matrix:
    # Conan development
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYVER: py38
      TOXENV: py38-conancurrent
      CMAKE_GENERATOR: "Visual Studio 16 2019"

platform:
  - x64
  - x86

install:
  - cmd: >-
      echo "Downloading conan..."
      set PATH=%PATH%;%PYTHON%/Scripts/
      python -m pip install --upgrade pip
      python -m pip install conan
      conan user
      conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      conan --version
      where conan

build_script:
  - cmd: >-
      mkdir build
      conan install . -s build_type=Release
      conan build .

test_script:
  - cmd: >-
      cd build
      ctest