version: 0.1.0-{build}
environment:
  PYTHON: "C:\\Python38"
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Windows
      APPVEYOR_BUILD_WORKER_CLOUD: 3Space Studio Private Build Cluster
      PYVER: py38
      TOXENV: py38-conancurrent
      CMAKE_GENERATOR: "Visual Studio 16 2019"

platform:
  - x86

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip3 install conan --upgrade
  - conan user
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan --force
  - conan --version

build_script:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - mkdir build
  - pip3 install -r requirements.txt
  - conan install cmake/3.17.3@/ -g virtualenv
  - activate
  - conan install . 
  - conan package .

after_build:
  - powershell Compress-Archive package/* darkstar-extender-%APPVEYOR_BUILD_VERSION%-%PLATFORM%.zip

artifacts:
  - path: darkstar-extender-$(APPVEYOR_BUILD_VERSION)-$(PLATFORM).zip
    name: DarkstarExtender

deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: Darkstar Extender $(APPVEYOR_REPO_TAG_NAME) Release
  description: "See release notes for information about this release: https://github.com/open-siege/open-siege/wiki/Release-Notes"
  provider: GitHub
  auth_token:
    secure: hD8hzQeP3c5jJuk/pMwouuz4wI8VdHDfGlyoTYLrWur9mLHj3lbMP7R37eHRd2Gy
  artifact: DarkstarExtender
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
