[keybindings]

[keybindings.keyboard]
increase_x_rotation = ["Left"]
decrease_x_rotation = ["Right"]
increase_y_rotation = ["Up"]
decrease_y_rotation = ["Down"]
increase_z_rotation = ["Home"]
decrease_z_rotation = ["PageUp"]
zoom_in = ["Add"]
zoom_out = ["Subtract"]
pan_left = ["End"]
pan_right = ["PageDown"]
